### ISSUE TITLE
Error: Cannot run with sound null safety, because the following dependencies don't support null safety:

### ISSUE THREAD

**Issue by naveenaa** [AlvinRamoutar/sudoku-api#11]
Launching lib/sudoku.dart on Android SDK built for x86 in debug mode...
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:sudoku_api

**Comment by AlvinRamoutar** [comment]
Hey @naveenaa ,
Thanks for raising this! I've had it on the backlog to address, and in fact @Pherne made a really great PR to address this (#10 ).
If you'd like, feel free to also test the changes introduced by @Pherne .
I plan to test it soon, and if all is well, introduce in a new release.

**Comment by AlvinRamoutar** [comment]
Hey @naveenaa ,
This will be resolved in v2.0.0 to be released shortly.
Thanks!
