### ISSUE TITLE
global Unsupported operation: Cannot add to a fixed-length list

### ISSUE THREAD

**Issue by rmasarovic** [AlvinRamoutar/sudoku-api#13]
Hi i try to use your api i find bug here:

List<CellViolation> _violations = new List<CellViolation>.empty();
    if (board()!.isRowViolated(position)) {
      _violations.add(CellViolation.Row);
    }
    if (board()!.isColumnViolated(position)) {
      _violations.add(CellViolation.Column);
    }
    if (board()!.isSegmentViolated(position)) {
      _violations.add(CellViolation.Segment);
    }

**Comment by AlvinRamoutar** [comment]
Hey @rmasarovic ,

Thanks for identifying this along with the submitted PR!
I'll review soon and get this merged in.

Cheers,
Alvin

**Comment by AlvinRamoutar** [comment]
Hey @rmasarovic ,

Appreciate the contribution - approved & merged.

Cheers,
Alvin
