### ISSUE TITLE
getColumn Grid method throws exception

### ISSUE THREAD

**Issue by JoseGeorges8** [AlvinRamoutar/sudoku-api#7]
Hi Alvin,

The `getColumn` method from the `Grid` class throws a `RangeException` when called. I noticed this was caused by this line:

`_tmpCol[c] = (_matrix[c][colNum]);`

I made a PR with a fix, cheers !

**Comment by AlvinRamoutar** [comment]
Hey @JoseGeorges8 ,

Thanks for catching this - I've commented on the PR and merged.
This will be **v1.1.1**.

Thank you! 🥳 
Cheers,
Alvin
