### ISSUE TITLE
About difficulty and pattern

### ISSUE THREAD

**Issue by ArjanAswal** [AlvinRamoutar/sudoku-api#9]
I have been working with this package lately and it is awesome.
I have a couple of questions:

- What does pattern do? What are some other patterns just like 'winter'?
- Apparently changing difficulty doesn't seem to do anything. What is the maximum, minimum, and default difficulty?

**Comment by ArjanAswal** [comment]
@AlvinRamoutar Can you help me out?

**Comment by AlvinRamoutar** [comment]
Hey @ArjanAswal ,

- Pattern decides the arrangement of given clues. You can see the default patterns in [`lib/src/models/PatternSet.dart`](https://github.com/AlvinRamoutar/sudoku-api/blob/master/lib/src/models/PatternSet.dart). You can specify a custom pattern via `PatternSet.add()`
- Changing difficulty correlates to the number of clues given for a puzzle. You can view that in [`lib/src/logic/PuzzleUtils.dart`](https://github.com/AlvinRamoutar/sudoku-api/blob/master/lib/src/logic/PuzzleUtils.dart). Do note that this only applies if you're not using a pattern.

**Comment by ArjanAswal** [comment]
@AlvinRamoutar I wanted the difficulty to range from 1-10 instead of just 1-3.
Is there any way we can pass custom `difficultyMap` or do I have to create custom patterns for each difficulty?

**Comment by AlvinRamoutar** [comment]
Not at the moment, but I can add that in @ArjanAswal .
Out of curiosity, what would this 1-10 range look like?
Difficulty levels should not affect the integrity of what a Sudoku puzzle is (meaning, a higher difficulty should not lead to ambiguity)

**Comment by ArjanAswal** [comment]
I was thinking that a lower difficulty would have most cells filled and a higher one would have the least possible, something that you have already implemented in the package. You are more knowledgeable in this area so you might know how to implement that without making the puzzle have multiple solutions.

**Comment by ArjanAswal** [comment]
@AlvinRamoutar  Can you give a rough timeline of when this feature will be implemented?
If you are not planning to do it anytime soon then can you tell me what the `difficultyMap` would be for 1-10 range?
Thank you.

**Comment by AlvinRamoutar** [comment]
Hey @ArjanAswal ,
Give me a week or so to work on something.
I'll ping you again in this PR once ready to have a look :)

**Comment by AlvinRamoutar** [comment]
Hey @ArjanAswal ,
This has been addressed in v1.2.2.
Please refer to  sudoku-api/test/generation_test.dart for an example of how to customize difficulty by specifying exactly the number of clues you want.
Let me know if this addresses your need.
Cheers,
Alvin

**Comment by ArjanAswal** [comment]
This is exactly what I needed. Thank you so much @AlvinRamoutar.
